---
version: '3'
services:
  proxy:
    image: nginx # this will use the latest version of 1.11.x
    ports:
       - 80:80
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro       # here, ro stands for Read Only
  web:
    image: httpd
